title: Folder Authenticator
description: Folder Authenticator is a secure and user-friendly password manager designed to help you manage your passwords and sensitive information with ease.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
